### ISSUE TITLE
 Stream timed out

### ISSUE THREAD

**Issue by rtk-teh** [EvilFreelancer/routeros-api-php#129]
Hello all.

Im make some service to manage own mikrotik to make VPN tunnels from web-interface via Laravel, and everything was ok while i make it on my own PC, but now im relase it in production server, and have many issues with "Stream timed out", sometimes everything work ok, sometimes i catch this error:

```
# php testcase.php
PHP Fatal error:  Uncaught RouterOS\Exceptions\StreamException: Stream timed out in /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/Streams/ResourceStream.php:55
Stack trace:
#0 /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/APILengthCoDec.php(115): RouterOS\Streams\ResourceStream->read()
#1 /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/APIConnector.php(53): RouterOS\APILengthCoDec::decodeLength()
#2 /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/Client.php(262): RouterOS\APIConnector->readWord()
#3 /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/Client.php(317): RouterOS\Client->readRAW()
#4 /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/ResponseIterator.php(74): RouterOS\Client->read()
#5 /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/Client.php(339): RouterOS\ResponseIterator->__construct()
#6 /var/www/html/nvs_mgmt_core/mikrotikapi_test/testcase.php(24): RouterOS\Client->readAsIterator()
#7 {main}
  thrown in /var/www/html/nvs_mgmt_core/mikrotikapi_test/vendor/evilfreelancer/routeros-api-php/src/Streams/ResourceStream.php on line 55
```

Code:

```
try {

            $client = new Client([
                'host' => "ip",
                'user' => "login",
                'pass' => "password",
                'port' => port_number
            ]);
            
            $query = 
                (new Query('/log/print'));
            $getting_log = $client->query($query)->read();

            foreach($getting_log as $message) {
                $log .= $message['time']." ".$message['topics']." ".$message['message'].PHP_EOL;
            }
            
        } catch (ConnectException $e) {
            $log = $e->getMessage().PHP_EOL;
        }
```
I have no problem with channel to mikrotik:
```
64 bytes from <mikrotik_ip>: icmp_seq=1 ttl=56 time=29.7 ms
64 bytes from <mikrotik_ip>: icmp_seq=2 ttl=56 time=32.9 ms
64 bytes from <mikrotik_ip>: icmp_seq=3 ttl=56 time=34.0 ms
64 bytes from <mikrotik_ip>: icmp_seq=4 ttl=56 time=34.9 ms
```

Also, when i get this issue, i see in log user logged in via api, but no message about logged out. 
When everything works normally, log also have message user logged out.

Maybe someone can help?

**Comment by rtk-teh** [comment]
After start same code on anothe machine i get error from composer about ext-sockets, activate it on php.ini and code work fine, i do the same with server and get PHP Warning:  Module "sockets" is already loaded in Unknown on line 0.

**Comment by EvilFreelancer** [comment]
Hi! Thanks for report, i'll check it on php 8.3
