### ISSUE TITLE
remove user

### ISSUE THREAD

**Issue by nrtszr** [EvilFreelancer/routeros-api-php#15]
don't work user

 $out = $client->write(['/ip/hotspot/user/remove', '[find name=34342]'])->read();

**Comment by EvilFreelancer** [comment]
Hello! Sure it will not work :) But do not worry, try this:
```php
$out = $client->query('/ip/hotspot/user/remove', ['name', '34342'])->read();
```
This mean: execute query `/ip/hotspot/user/remove` for items where `name` is `34342`, then return results, you may use `->read(false)` for getting RAW results from router.

**Comment by nrtszr** [comment]
hi,
$out = $client->query('/ip/hotspot/user/remove', ['name', '34342'])->read();

Result:
Array ( )

Don't remove

**Comment by nrtszr** [comment]
if this code:
    $query = new Query('/ip/hotspot/user/remove');
    $query->where('name', '34342');
    $out = $client->query($query)->read();

Result:
Fatal error: Uncaught Error: Class 'Query' not found in a.php:23 Stack trace: #0 {main} thrown in

**Comment by nrtszr** [comment]
add 
`use \RouterOS\Query;`

Code:
```
    $query = new Query('/ip/hotspot/user/remove');
    $query->where('name', '34342');

    $out = $client->query($query)->read();
```

Result:
Fatal error: Uncaught TypeError: Argument 1 passed to RouterOS\Client::query() must be of the type string, object given, called in D:\xampp\htdocs\mikrotik\a.php on line 30 and defined in D:\xampp\htdocs\mikrotik\vendor\evilfreelancer\routeros-api-php\src\Client.php:114 Stack trace: #0 mikrotik\a.php(30): RouterOS\Client->query(Object(RouterOS\Query)) #1 {main} thrown in mikrotik\vendor\evilfreelancer\routeros-api-php\src\Client.php on line 114

**Comment by EvilFreelancer** [comment]
> Fatal error: Uncaught TypeError: Argument 1 passed to RouterOS\Client::query() must be of the type string, object given, called in D:\xampp\htdocs\mikrotik\a.php on line 30 and defined in D:\xampp\htdocs\mikrotik\vendor\evilfreelancer\routeros-api-php\src\Client.php:114 Stack trace: #0 mikrotik\a.php(30): RouterOS\Client->query(Object(RouterOS\Query)) #1 {main} thrown in mikrotik\vendor\evilfreelancer\routeros-api-php\src\Client.php on line 114

This is very interesting bug vith object (fix will be in 1.0.1).

Now about removing issue, I found sollution on mikrotik forum, unfortinatly you can't use filtering if you want to remove something without ID of this object. First you need to get ID of user, then remove this user by their  ID. Something like this:

```php
$user = $client->query('/ip/hotspot/user/print', ['name', '34342'])->read(); // Here should be at least one item

// If item's ID is exist, then remove item by it
if (isset($user[0]['.id'])) {
    $userId = $user[0]['.id'];
    $removeUser = $client->query('/ip/hotspot/user/remove', ['.id', $userId])->read();
}
```
